import { index, integer, jsonb, pgTable, primaryKey, text, timestamp } from "drizzle-orm/pg-core";
import type { AiPlan } from "@/lib/ai/planSchema";
import type { PlanJobStatus } from "@/lib/ai/planView";
import type { DraftState, LeagueSettings } from "@/lib/draft/types";

/**
 * The hosted database. Change it here, then run `npm run db:generate` to write a migration
 * into drizzle/ and commit both. See docs/database.md.
 *
 * Not "server-only": drizzle-kit loads this file outside Next. Only src/lib/db/index.ts,
 * which opens connections, is restricted to the server.
 */

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
};

/* ---------- Auth.js (shapes required by @auth/drizzle-adapter; property names must not change) ---------- */

/** Auth.js's AdapterAccountType, restated so the schema doesn't depend on the auth packages. */
type AdapterAccountType = "oauth" | "oidc" | "email" | "webauthn";

export const users = pgTable("users", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  name: text("name"),
  email: text("email").unique(),
  emailVerified: timestamp("email_verified", { withTimezone: true, mode: "date" }),
  image: text("image"),
});

export const accounts = pgTable(
  "accounts",
  {
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: text("type").$type<AdapterAccountType>().notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("provider_account_id").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (t) => [primaryKey({ columns: [t.provider, t.providerAccountId] }), index("accounts_user_id_idx").on(t.userId)],
);

export const sessions = pgTable(
  "sessions",
  {
    sessionToken: text("session_token").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    expires: timestamp("expires", { withTimezone: true, mode: "date" }).notNull(),
  },
  (t) => [index("sessions_user_id_idx").on(t.userId)],
);

export const verificationTokens = pgTable(
  "verification_tokens",
  {
    identifier: text("identifier").notNull(),
    token: text("token").notNull(),
    expires: timestamp("expires", { withTimezone: true, mode: "date" }).notNull(),
  },
  (t) => [primaryKey({ columns: [t.identifier, t.token] })],
);

/* ---------- war room ---------- */

/** A user's league. Mirrors LeagueRecord in src/lib/storage/types.ts; ids are generated by the client. */
export const leagues = pgTable(
  "leagues",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    season: integer("season").notNull(),
    datasetId: text("dataset_id").notNull(),
    settings: jsonb("settings").$type<LeagueSettings>().notNull(),
    ...timestamps,
    /** Soft delete: keeps the row (and any entitlement on it) recoverable. */
    deletedAt: timestamp("deleted_at", { withTimezone: true, mode: "date" }),
  },
  (t) => [index("leagues_user_id_idx").on(t.userId)],
);

/**
 * One draft per league. Kept out of `leagues` so logging a pick never rewrites settings.
 * `revision` increments on every write; a write based on an older revision is rejected.
 */
export const drafts = pgTable("drafts", {
  leagueId: text("league_id")
    .primaryKey()
    .references(() => leagues.id, { onDelete: "cascade" }),
  state: jsonb("state").$type<DraftState>().notNull(),
  revision: integer("revision").notNull().default(0),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
});

/** What a league has paid for. Epic 4 defines the kinds and when rows are written. */
export const entitlements = pgTable(
  "entitlements",
  {
    leagueId: text("league_id")
      .notNull()
      .references(() => leagues.id, { onDelete: "cascade" }),
    kind: text("kind").notNull(),
    grantedAt: timestamp("granted_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
    /** Where the grant came from, e.g. a Stripe checkout session id. */
    source: text("source").notNull(),
  },
  (t) => [primaryKey({ columns: [t.leagueId, t.kind] })],
);

/** Where a league's AI plan job stands. See src/lib/server/aiPlans.ts. */
export type AiPlanStatus = PlanJobStatus;

/**
 * A league's AI-written game plan and the background job that writes it. One row per league.
 * `job_id` changes on every claim and fences writes: a job only saves its result if it's still current.
 * `plan` keeps the last good plan while a new job runs or fails.
 */
export const aiPlans = pgTable(
  "ai_plans",
  {
    leagueId: text("league_id")
      .primaryKey()
      .references(() => leagues.id, { onDelete: "cascade" }),
    status: text("status").$type<AiPlanStatus>().notNull(),
    jobId: text("job_id"),
    /** planInputHash() the latest request was made for. */
    inputHash: text("input_hash").notNull(),
    attempts: integer("attempts").notNull().default(0),
    /** A generating job whose lease has passed is presumed dead (e.g. a restart) and can be claimed again. */
    leaseExpiresAt: timestamp("lease_expires_at", {
      withTimezone: true,
      mode: "date",
    }),
    errorKind: text("error_kind"),
    plan: jsonb("plan").$type<AiPlan>(),
    /** planInputHash() the stored plan was built from; differs from the league's current hash when stale. */
    planInputHash: text("plan_input_hash"),
    issues: jsonb("issues").$type<string[]>(),
    provider: text("provider"),
    model: text("model"),
    promptVersion: integer("prompt_version"),
    requestedAt: timestamp("requested_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "date" }),
    completedAt: timestamp("completed_at", {
      withTimezone: true,
      mode: "date",
    }),
  },
  (t) => [index("ai_plans_status_idx").on(t.status)],
);
