import { boolean, date, index, integer, jsonb, numeric, pgTable, primaryKey, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";
import type { AiPlan } from "@/lib/ai/planSchema";
import type { AiLineup } from "@/lib/ai/season/lineup";
import type { SeasonAiUseKind } from "@/lib/ai/season/state";
import type { AiTradeWriteup } from "@/lib/ai/season/trade";
import type { PlanJobStatus } from "@/lib/ai/planView";
import type { PlanModelErrorKind } from "@/lib/ai/provider";
import type { DraftState, LeagueSettings } from "@/lib/draft/types";

/**
 * The hosted database. Change it here, then run `npm run db:generate` to write a migration
 * into drizzle/ and commit both. See docs/database.md.
 *
 * Not "server-only": drizzle-kit loads this file outside Next. Only src/lib/db/index.ts,
 * which opens connections, is restricted to the server.
 */

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
};

/* ---------- Auth.js (shapes required by @auth/drizzle-adapter; property names must not change) ---------- */

/** Auth.js's AdapterAccountType, restated so the schema doesn't depend on the auth packages. */
type AdapterAccountType = "oauth" | "oidc" | "email" | "webauthn";

export const users = pgTable("users", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  name: text("name"),
  email: text("email").unique(),
  emailVerified: timestamp("email_verified", { withTimezone: true, mode: "date" }),
  image: text("image"),
});

export const accounts = pgTable(
  "accounts",
  {
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: text("type").$type<AdapterAccountType>().notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("provider_account_id").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (t) => [primaryKey({ columns: [t.provider, t.providerAccountId] }), index("accounts_user_id_idx").on(t.userId)],
);

export const sessions = pgTable(
  "sessions",
  {
    sessionToken: text("session_token").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    expires: timestamp("expires", { withTimezone: true, mode: "date" }).notNull(),
  },
  (t) => [index("sessions_user_id_idx").on(t.userId)],
);

export const verificationTokens = pgTable(
  "verification_tokens",
  {
    identifier: text("identifier").notNull(),
    token: text("token").notNull(),
    expires: timestamp("expires", { withTimezone: true, mode: "date" }).notNull(),
  },
  (t) => [primaryKey({ columns: [t.identifier, t.token] })],
);

/* ---------- war room ---------- */

/** A user's league. Mirrors LeagueRecord in src/lib/storage/types.ts; ids are generated by the client. */
export const leagues = pgTable(
  "leagues",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    season: integer("season").notNull(),
    datasetId: text("dataset_id").notNull(),
    settings: jsonb("settings").$type<LeagueSettings>().notNull(),
    /** When the league drafts: "YYYY-MM-DD" or an ISO instant (src/lib/draft/draftDay.ts). Null when not set. */
    draftAt: text("draft_at"),
    ...timestamps,
    /** Soft delete: keeps the row (and any entitlement on it) recoverable. */
    deletedAt: timestamp("deleted_at", { withTimezone: true, mode: "date" }),
  },
  (t) => [index("leagues_user_id_idx").on(t.userId)],
);

/**
 * One draft per league. Kept out of `leagues` so logging a pick never rewrites settings.
 * `revision` increments on every write; a write based on an older revision is rejected.
 */
export const drafts = pgTable("drafts", {
  leagueId: text("league_id")
    .primaryKey()
    .references(() => leagues.id, { onDelete: "cascade" }),
  state: jsonb("state").$type<DraftState>().notNull(),
  revision: integer("revision").notNull().default(0),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
});

/** What a league has paid for. Written by the Stripe webhook; see src/lib/server/entitlements.ts. */
export const entitlements = pgTable(
  "entitlements",
  {
    leagueId: text("league_id")
      .notNull()
      .references(() => leagues.id, { onDelete: "cascade" }),
    kind: text("kind").notNull(),
    grantedAt: timestamp("granted_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
    /** Where the grant came from, e.g. a Stripe checkout session id. */
    source: text("source").notNull(),
    /** What was paid, in the currency's smallest unit (cents). Null for grants that weren't bought. */
    amountTotal: integer("amount_total"),
    /** ISO currency code, lowercase as Stripe sends it (e.g. "usd"). */
    currency: text("currency"),
  },
  (t) => [primaryKey({ columns: [t.leagueId, t.kind] })],
);

/** Where a league's AI plan job stands. See src/lib/server/aiPlans.ts. */
export type AiPlanStatus = PlanJobStatus;

/**
 * A league's AI-written game plan and the background job that writes it. One row per league.
 * `job_id` changes on every claim and fences writes: a job only saves its result if it's still current.
 * `plan` keeps the last good plan while a new job runs or fails.
 */
export const aiPlans = pgTable(
  "ai_plans",
  {
    leagueId: text("league_id")
      .primaryKey()
      .references(() => leagues.id, { onDelete: "cascade" }),
    status: text("status").$type<AiPlanStatus>().notNull(),
    jobId: text("job_id"),
    /** planInputHash() the latest request was made for. */
    inputHash: text("input_hash").notNull(),
    attempts: integer("attempts").notNull().default(0),
    /** A generating job whose lease has passed is presumed dead (e.g. a restart) and can be claimed again. */
    leaseExpiresAt: timestamp("lease_expires_at", {
      withTimezone: true,
      mode: "date",
    }),
    errorKind: text("error_kind"),
    plan: jsonb("plan").$type<AiPlan>(),
    /** planInputHash() the stored plan was built from; differs from the league's current hash when stale. */
    planInputHash: text("plan_input_hash"),
    issues: jsonb("issues").$type<string[]>(),
    provider: text("provider"),
    model: text("model"),
    promptVersion: integer("prompt_version"),
    requestedAt: timestamp("requested_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "date" }),
    completedAt: timestamp("completed_at", {
      withTimezone: true,
      mode: "date",
    }),
  },
  (t) => [index("ai_plans_status_idx").on(t.status)],
);

/** How a model call for a plan ended: saved, outrun by a newer job, or a failure kind. */
export type GenerationOutcome = "ready" | "superseded" | PlanModelErrorKind | "internal";

/** What a model call was for: the draft plan (Epic 5), or in-season AI (Epic 11). */
export type GenerationPurpose = "plan" | "season-lineup" | "season-trade";

/**
 * Every model call made for an AI plan, with its token usage and cost, for checking unit economics
 * (see src/lib/server/aiCosts.ts). Append-only. League and user ids aren't foreign keys, so the
 * history outlives deleted leagues and accounts.
 */
export const aiGenerations = pgTable(
  "ai_generations",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    leagueId: text("league_id").notNull(),
    userId: text("user_id").notNull(),
    jobId: text("job_id").notNull(),
    purpose: text("purpose").$type<GenerationPurpose>().notNull().default("plan"),
    provider: text("provider").notNull(),
    model: text("model").notNull(),
    promptVersion: integer("prompt_version").notNull(),
    outcome: text("outcome").$type<GenerationOutcome>().notNull(),
    /** Null when the provider reported no usage, e.g. a call cut off at its deadline. */
    inputTokens: integer("input_tokens"),
    cachedInputTokens: integer("cached_input_tokens"),
    outputTokens: integer("output_tokens"),
    /** Priced when logged (src/lib/ai/pricing.ts). Null for a model without a known price or without usage. */
    costUsd: numeric("cost_usd", { precision: 12, scale: 6, mode: "number" }),
    durationMs: integer("duration_ms").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
  },
  (t) => [index("ai_generations_created_at_idx").on(t.createdAt), index("ai_generations_league_outcome_idx").on(t.leagueId, t.outcome)],
);

/**
 * Pairing tokens for the ESPN draft bridge (Epic 8). The bridge runs in the user's ESPN tab, where
 * our session cookie isn't sent, so it authenticates its relay requests with one of these instead.
 * Only a SHA-256 of the token is stored. A token is scoped to one war room league and one ESPN
 * league, and expires; see src/lib/server/espn/bridgeTokens.ts.
 */
export const espnBridgeTokens = pgTable(
  "espn_bridge_tokens",
  {
    tokenHash: text("token_hash").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    leagueId: text("league_id")
      .notNull()
      .references(() => leagues.id, { onDelete: "cascade" }),
    espnLeagueId: text("espn_league_id").notNull(),
    espnTeamId: integer("espn_team_id").notNull(),
    season: integer("season").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
    expiresAt: timestamp("expires_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (t) => [index("espn_bridge_tokens_league_id_idx").on(t.leagueId), index("espn_bridge_tokens_expires_at_idx").on(t.expiresAt)],
);

/**
 * Which version of the ESPN live sync disclosure (src/lib/espn/disclosure.ts) each user has
 * acknowledged. Pairing a bridge requires the current version.
 */
export const espnDisclosureAcks = pgTable("espn_disclosure_acks", {
  userId: text("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  version: integer("version").notNull(),
  acknowledgedAt: timestamp("acknowledged_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
});

/** Where a server-side ESPN client stands for one draft (Epic 9); see src/lib/server/espn/serverClients.ts. */
export type EspnServerClientState = "stored" | "holding" | "lost" | "released" | "complete";

/**
 * The ESPN join credential a user handed War Room so it can draft for them without their ESPN tab
 * open (Epic 9): their draft room's join code and SWID, sealed with ESPN_CODE_KEY
 * (src/lib/server/espn/secretBox.ts). One per war room league. Deleted when the draft completes, and
 * by a sweep once it expires, so a draft that never finishes doesn't keep a credential around.
 */
export const espnServerClients = pgTable(
  "espn_server_clients",
  {
    leagueId: text("league_id")
      .primaryKey()
      .references(() => leagues.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    espnLeagueId: text("espn_league_id").notNull(),
    espnTeamId: integer("espn_team_id").notNull(),
    season: integer("season").notNull(),
    /** `{ code, swid }` as JSON, sealed. Never logged, never returned by an API. */
    sealed: text("sealed").notNull(),
    /** ESPN's league settings as the bridge read them, so a restarted process can rebuild the draft (9.5). */
    leagueSettings: jsonb("league_settings").$type<unknown>(),
    /** The team that owns each overall pick, in order, for catching up from INIT after a restart. */
    pickTeams: jsonb("pick_teams").$type<number[]>(),
    consentVersion: integer("consent_version").notNull(),
    state: text("state").$type<EspnServerClientState>().notNull().default("stored"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
    expiresAt: timestamp("expires_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (t) => [index("espn_server_clients_state_idx").on(t.state), index("espn_server_clients_expires_at_idx").on(t.expiresAt)],
);

/** Whether a stored ESPN login still works: `disconnected` once ESPN refuses it (401/403). */
export type EspnLoginStatus = "connected" | "disconnected";

/**
 * The ESPN login a user handed War Room for the season (Epic 10, 10.2): their `espn_s2` and SWID
 * cookies, sealed with ESPN_CODE_KEY (src/lib/server/espn/secretBox.ts), so the server can read
 * their private leagues each week without their ESPN tab. One per user, since one ESPN login covers
 * all of a user's leagues. Deleted when they disconnect, with their account, and by a sweep once the
 * fantasy season is over (`expiresAt`).
 */
export const espnLogins = pgTable(
  "espn_logins",
  {
    userId: text("user_id")
      .primaryKey()
      .references(() => users.id, { onDelete: "cascade" }),
    /** `{ espnS2, swid }` as JSON, sealed. Never logged, never returned by an API. */
    sealed: text("sealed").notNull(),
    season: integer("season").notNull(),
    consentVersion: integer("consent_version").notNull(),
    status: text("status").$type<EspnLoginStatus>().notNull().default("connected"),
    /** When ESPN last accepted it. */
    verifiedAt: timestamp("verified_at", { withTimezone: true, mode: "date" }),
    ...timestamps,
    expiresAt: timestamp("expires_at", { withTimezone: true, mode: "date" }).notNull(),
  },
  (t) => [index("espn_logins_expires_at_idx").on(t.expiresAt)],
);

/**
 * Which ESPN league and team a war room league follows during the season (10.3). Written when the
 * user connects their season from ESPN; the season page reads rosters for this ESPN league with the
 * user's stored login (`espn_logins`). One per war room league, and one war room league per ESPN
 * league and season for each user.
 */
export const espnSeasonLinks = pgTable(
  "espn_season_links",
  {
    leagueId: text("league_id")
      .primaryKey()
      .references(() => leagues.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    espnLeagueId: text("espn_league_id").notNull(),
    espnTeamId: integer("espn_team_id").notNull(),
    season: integer("season").notNull(),
    /** When the user last opened this league's season page. The Sunday job (11.3) skips leagues left alone for two weeks. */
    lastViewedAt: timestamp("last_viewed_at", { withTimezone: true, mode: "date" }),
    ...timestamps,
  },
  (t) => [uniqueIndex("espn_season_links_user_espn_idx").on(t.userId, t.espnLeagueId, t.season)],
);

/**
 * When each account started its in-season AI trial (Epic 11, 11.1): the ESPN `scoringPeriodId` of
 * its first AI use that season. Kept on the user, not the league, so linking another league doesn't
 * restart it. See src/lib/server/seasonAi.ts.
 */
export const seasonAiTrials = pgTable(
  "season_ai_trials",
  {
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    season: integer("season").notNull(),
    firstWeek: integer("first_week").notNull(),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.season] })],
);

export type { SeasonAiUseKind };

/** Which weekly in-season AI allowances a league has used. One row per league, week and kind. */
export const seasonAiUses = pgTable(
  "season_ai_uses",
  {
    leagueId: text("league_id")
      .notNull()
      .references(() => leagues.id, { onDelete: "cascade" }),
    season: integer("season").notNull(),
    /** ESPN's `scoringPeriodId`. */
    week: integer("week").notNull(),
    kind: text("kind").$type<SeasonAiUseKind>().notNull(),
    usedAt: timestamp("used_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.leagueId, t.season, t.week, t.kind] })],
);

/** What a stored in-season AI output is: a weekly lineup (SeasonAiUseKind), or a trade write-up. */
export type SeasonAiOutputKind = SeasonAiUseKind | "trade";

/**
 * In-season AI outputs (11.2), kept so reloading the page never pays for another. Lineups are one
 * per league, week and kind; trade write-ups one per league, week and trade (`key`, a hash of the
 * trade), since the verdict they explain changes week to week.
 */
export const seasonAiOutputs = pgTable(
  "season_ai_outputs",
  {
    leagueId: text("league_id")
      .notNull()
      .references(() => leagues.id, { onDelete: "cascade" }),
    season: integer("season").notNull(),
    week: integer("week").notNull(),
    kind: text("kind").$type<SeasonAiOutputKind>().notNull(),
    /** The trade's hash for a write-up; empty for a lineup. */
    key: text("key").notNull().default(""),
    output: jsonb("output").$type<AiLineup | AiTradeWriteup>().notNull(),
    issues: jsonb("issues").$type<string[]>().notNull(),
    provider: text("provider").notNull(),
    model: text("model").notNull(),
    promptVersion: integer("prompt_version").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.leagueId, t.season, t.week, t.kind, t.key] })],
);

/** A user's email settings. No row means the defaults. */
export const userPrefs = pgTable("user_prefs", {
  userId: text("user_id")
    .primaryKey()
    .references(() => users.id, { onDelete: "cascade" }),
  /** The "Your Sunday lineup is ready" email, and the reconnect email the same job sends (11.3). */
  seasonEmails: boolean("season_emails").notNull().default(true),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
});

/** Which email a season job sent: the Sunday lineups, a request to reconnect ESPN, or an early-kickoff alert (11.4). */
export type SeasonEmailKind = "lineup" | "reconnect" | "early";

/**
 * Emails the season jobs have sent (11.3, 11.4), one per user, kind, day and slot, so a rerun never
 * sends another. By day rather than NFL week: a reconnect email is sent when ESPN can't be read.
 */
export const seasonEmails = pgTable(
  "season_emails",
  {
    userId: text("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    kind: text("kind").$type<SeasonEmailKind>().notNull(),
    /** "YYYY-MM-DD", UTC. */
    sentOn: date("sent_on", { mode: "string" }).notNull(),
    /** The kickoff an early alert was for (ISO), since one day can have several; empty otherwise. */
    slot: text("slot").notNull().default(""),
    sentAt: timestamp("sent_at", { withTimezone: true, mode: "date" }).notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.kind, t.sentOn, t.slot] })],
);
